TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'M12.Foundation': TRUE

    nodeTypes:
      groups:
        foundationStructure:
          position: 10
          label: 'Foundation - Structure'
        foundationButtons:
          position: 30
          label: 'Foundation - Buttons'

M12:
  Foundation:
    # Needed by ColumnNodeTypePostprocessor to know in which UI group
    # put all generated properties
    uiInspectorGroupName: 'grid'

    gridSize: 12

    devices:
      small:
        label: 'Small device'
      medium:
        label: 'Medium device'
      large:
        label: 'Large device'

    deviceColumnSettings:
      width:
        label: 'Column width'
      offset:
        label: 'Column offset'
      push:
        label: 'Column push'
      pull:
        label: 'Column pull'

    columnSettings:
      center:
        label: 'Column centered'
      resetOrder:
        label: 'Column reset order'
