TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'M12.Foundation': TRUE

    nodeTypes:
      groups:
        foundationStructure:
          position: 10
          label: 'Foundation - Structure'
        foundationNavigation:
          position: 20
          label: 'Foundation - Navigation'
        foundationButtons:
          position: 30
          label: 'Foundation - Buttons'
        foundationCalloutsPrompts:
          position: 70
          label: 'Foundation - Callouts & Prompts'


M12:
  Foundation:
    gridSize: 12

    devices:
      small:
        label: 'Small device'
      medium:
        label: 'Medium device'
      large:
        label: 'Large device'


    gridSettings:
      size:
        label: 'Column width'
        cssClassSuffixes: [ '-' ]         # DEVICE-X, eg: small-X, medium-Y, large-Z
        appliedPerColumn: true
        uiInspectorGroup: gridSize
      offset:
        label: 'Column offset'
        cssClassSuffixes: [ '-offset-' ]  # DEVICE-offset-X, eg: small-offset-X, medium-offset-Y, large-offset-Z
        appliedPerColumn: true
        uiInspectorGroup: gridOffset
      pushPull:
        label: 'Column push / pull'
        cssClassSuffixes: [ '-push-', '-pull-' ]    # DEVICE-push-X, eg: small-push-X, medium-push-Y, large-push-Z
        appliedPerColumn: true
        uiInspectorGroup: gridPushPull
      resetOrder:
        label: 'Column reset order'
        cssClassSuffixes: [ '-reset-order' ]  # e.g. small-reset-order
        appliedPerColumn: false
        uiInspectorGroup: gridPushPull
      align:
        label: 'Centered'
        cssClassSuffixes: [ '-centered', '-uncentered' ] # e.g. small-centered, large-centered
        appliedPerColumn: false
        uiInspectorGroup: gridAlign


    blockGridSettings:
      itemsPerRow:
        label: 'Number of items per row'
        cssClassSuffixes: [ '-block-grid-' ]    # DEVICE-block-grid-X, eg: small-block-grid-X, medium-block-grid-Y, large-block-grid-Z
        appliedPerColumn: true
        uiInspectorGroup: blockGridSettings

