TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'M12.Foundation': TRUE

    nodeTypes:
      groups:
        foundationStructure:
          position: 10
          label: 'Foundation - Structure'
        foundation:
          position: 11
          label: 'Foundation'

M12:
  Foundation:
    # Needed by ColumnNodeTypePostprocessor to know in which UI group
    # put all generated properties
    uiInspectorGroupName: 'grid'

    gridSize: 12

    devices:
      small:
        label: 'Small device'
        size: '< 768'
      medium:
        label: 'Medium device'
        size: '≥ 768'
      large:
        label: 'Large device'
        size: '≥ 992'
